add : add internal developer portals, add article
awskrug/platform-engineering-glossary pull request #3
Opened 2024-01-17 05:17 UTC by pinetree2

### Description
- 브랜치 명은 일단 임의로 작성했습니다. 피드백 주시면 변경하겠습니다!
- 작성해주신 README 파일에 따라, pinetree2/what_is_platform_engineering.md 를 추가했습니다.
- 추가로, 번역문을 작성하면서, 기존에 형근님께서 추가하신 glossary 중 'internal developer portal' 의 복수 표현인 'internal developer portals' 로 표기되어있어 추가해보았습니다. 
- 실제 구글 검색 결과 많이 등장하는 표현은 아닌 것 같았습니다.
- 번역 문서 작성과 glossary 작성을 동시에 진행했습니다. 전체적인 방식 및 개발 관련하여 다소 미숙하기 때문에 말씀해주시면 바로 수정하겠습니다! 

### 변경 후 
|en|ko|
|------|---|
|platform engineering|플랫폼 엔지니어링
|internal developer portals|내부 개발자 포털

2024-01-17 15:45 UTC, jjangga0214 commented
첫 PR 정말 감사합니다!

글 잘 읽어볼게요 :)

혹시 (저희가 전에 첫 회의부터 이야기했었던) [dev.to](dev.to) 에 자동으로 퍼블리시 하실 생각이 있으신가요?

그럼 (새로 업뎃된) README 를 읽어봐 주세요 ㅎㅎ

2024-01-17 23:57 UTC, pinetree2 commented
오! 넵 참고해서 자동으로 퍼블리시 할 수 있도록 하겠습니다 :)

2024-01-19 08:38 UTC, jjangga0214 commented
(첫번째와 두번째 사이드 이펙트 모두 main에서 glossary 오타를 고친것을 머지한 과정에서 감지된 것입니다.
위는 봇이 정상 동작한 것이고, 무시해도 됩니다.)

2024-01-20 01:49 UTC, Eeap commented
번역 아티클 경우도 뭔가 컨벤션이 있어도 좋을 것 같아요 ~ 아래는 참고할만한 k8s 한국어 문서화 가이드입니답
https://kubernetes.io/ko/docs/contribute/localization_ko/

2024-01-21 03:58 UTC, jjangga0214 commented
@Eeap 오 좋네요~ 다음 케이던스에서 언급하면 좋을 것 같아요~

2024-01-22 00:33 UTC, pinetree2 commented
좋습니다! 어투를 어떻게 해야할지 고민이었는데, 컨벤션을 정하고 다시 수정해서 pr 날리는게 좋을 것 같습니다!

2024-01-27 03:55 UTC, jjangga0214 requested changes

2024-01-27 03:55 UTC, jjangga0214 commented on articles/pinetree2/what_is_platform_engineering.md
> +> [영상 링크](https://www.youtube.com/watch?embeds_referring_euri=https%3A%2F%2Fwww.gartner.com%2F&embeds_referring_origin=https%3A%2F%2Fwww.gartner.com&source_ve_path=MzY4NDIsMjg2NjQsMTY0NTAz&feature=em
영상 부분을 아래와 같이 대체하면 어떨까요?

```md
{% embed https://www.youtube.com/live/Lq-G2GyLsFk?si=IRXmmf_jetb9jSjO %}
```

> <img width="728" alt="스크린샷 2024-01-23 오후 1 31 59" src="https://github.com/awskrug/platform-engineering-glossary/assets/28584151/9d729865-f9fc-4ee1-9876-87c0f3157433">
> - README

2024-01-27 03:55 UTC, jjangga0214 commented on articles/pinetree2/what_is_platform_engineering.md
> +slug: about-platforms
사견으로는 slug 를 만약 

- `gartner-platform-engineering`
또는
- `gartner-what-is-platform-engineering`
또는
- `what-is-platform-engineering` 

등과 같이 하면 어떨까? 싶기도 한데 어떻게 생각하세요? ㅎㅎ

2024-01-27 03:55 UTC, jjangga0214 commented on articles/pinetree2/what_is_platform_engineering.md
> +series: AWSKRUG
series 부분은 아마(?) 실수하신 것 같습니다!
물론 series 를 만들 수는 있지만 AWSKRUG 라는 이름의 시리즈로 의도하신 것이 맞으실까요?
(참고로 series 는 optional 이라 Frontmatter 에 명시되지 않아도 괜찮아요. 그러면 시리즈 물이 아니라 독립적인 단일 아티클로 퍼블리시됩니다.)

2024-01-27 03:55 UTC, jjangga0214 commented on articles/pinetree2/what_is_platform_engineering.md
> +번역 : @pinetree2
이 부분은 원하시는 링크를 달아도 좋을 것 같아요!

```md
번역 : [@pinetree2](...)
```

2024-01-27 03:55 UTC, jjangga0214 commented on articles/pinetree2/what_is_platform_engineering.md
> +가트너의 VP 분석가인 폴 델로리는 말합니다. "{{ Platform Engineering }} 은 현대 소프트웨어 아키텍처의 복잡성이 증가함에 따라 등장했습니다. 오늘날에는 비전문가인 최종 사용자들도 복잡하고 난해한 서비스의 집합을 운영해야 하는 경우가 많습니다, 최종 사용자를 돕고, 그들이 수행하는 가치 있는 업무에 대한 마찰을 줄이기 위해, 선진적인
사람을 인용할 때 이렇게 영어 이름과 링크를 달아주면 어떨까요?

```md
[폴 델로리](https://www.gartner.com/en/experts/paul-delory)(Paul Delory. 가트너 VP 분석가)
```

2024-01-31 07:18 UTC, pinetree2 commented on articles/pinetree2/what_is_platform_engineering.md
> +> [영상 링크](https://www.youtube.com/watch?embeds_referring_euri=https%3A%2F%2Fwww.gartner.com%2F&embeds_referring_origin=https%3A%2F%2Fwww.gartner.com&source_ve_path=MzY4NDIsMjg2NjQsMTY0NTAz&feature=em
우와 넵 감사합니다! 한번 수정해보겠습니다

2024-01-31 07:18 UTC, pinetree2 commented on articles/pinetree2/what_is_platform_engineering.md
> +slug: about-platforms
좋습니다! 두번째로 해보겠습니다

2024-01-31 07:19 UTC, pinetree2 commented on articles/pinetree2/what_is_platform_engineering.md
> +series: AWSKRUG
넵 작성해주신거 보고 따라하다가 넣어버린것같습니다 ..😂

2024-01-31 07:31 UTC, pinetree2 commented on articles/pinetree2/what_is_platform_engineering.md
> +번역 : @pinetree2
넵

2024-01-31 09:03 UTC, jjangga0214 commented
아 그리고 이 링크를 타고 들어갔을때 아마 해송님께만 draft 가 보일꺼에요!

<img width="799" alt="스크린샷 2024-01-31 오후 5 07 04" src="https://github.com/awskrug/platform-engineering-glossary/assets/28584151/3c3bfb24-c7f5-4e73-88db-ebbede542883">

Draft 는 기본적으로 private 인데, 피드백을 위해 공유하는 경우를 위해 URL 뒤에 `?preview=....` 가 붙어요.
글을 클릭하고 브라우저에서 확인해보시면 보이실거에요.
링크 자체가 비밀번호인 역할을 해주는 거죠.
그런데 현 dev.to API 로는 이 `preview` querystring 을 얻을 수 없어서 대시보드로 가게되어 있습니다.
혹시 위 사진의 코멘트를 수정해서 링크를 눌렀을때 draft 로 바로 갈 수 있도록 해도 다른 분들이 편하게 보시고 피드백 주시기 좋을 것 같아요 ㅎㅎ

2024-04-16 07:51 UTC, merged

2024-04-16 07:54 UTC, pinetree2 commented
https://dev.to/platform-engineering-korea/about-platforms-3if3-temp-slug-9151613?preview=db984979df28fe9d302612a9de91b210064db7a061062cc41dcc890828f0a5760e803b150072b2cfdd37a40d750ee5717f461c49b23b045d45c718c5