articles(jjangga0214/talk-about-platforms): init
awskrug/platform-engineering-glossary pull request #4
Opened 2024-01-31 05:14 UTC by jjangga0214

https://martinfowler.com/articles/talk-about-platforms.html

를 번역하고 glossary 를 추가하였습니다~

2024-01-31 06:32 UTC, Geun-Oh requested changes
수고하셨습니다!
글의 내용이 재밌어 깊게 읽은 것 같습니다. 좋은 글 번역 감사합니다 :)

2024-01-31 06:32 UTC, Geun-Oh commented on articles/jjangga0214/0001-talk-about-platforms.md
> +*BigCo* 는 클라우드 및 자동화에 대해 대규모로 투자하고 있었습니다. 하지만 그럼에도 불구하고 인프라 및 운영 영역에서 전통적인 팀을 유지하고 있었어요. 이 '전통적인 팀'은 주된 기술 역량에 따라 구성되어 있었죠. 우리는 몇 가지 일반적인 변경 사항이 회사에서 어떻게 수행되는지 그 전 과정을 따라가 보았습니다. 각 변경 사항에는 여러 팀이 참여했습
사소하지만,,,
> 맞닥드렸죠 => 맞닥뜨렸죠 

로 수정하면 좋을 것 같습니다!

2024-01-31 06:32 UTC, Geun-Oh commented on articles/jjangga0214/0001-talk-about-platforms.md
> +(**역주**: 플랫폼 엔지니어링의 영역에서는 '{{ Golden Path }}'(Golden Path)라는 용어도 종종 사용됩니다. '{{ Paved Road }}'(Paved Road) 와 둘다 "길"로 비유한다는 점은 공통점이지만, 서로 다른 개념입니다. 전자는 공통적인 관심사에 대한 템플릿에 가깝고, 후자는 중앙화되면서 검증된 도구를 의미합니다.)
Golden Path 와 Paved Road 에서 조금 생각이 들었던 것이,
두 단어 모두 본래 존재하던 단어를 플랫폼 엔지니어링 내부에서 차용하여 해석해 이제는 단어의 의미가 조금 더 플랫폼 엔지니어링 기반으로 구체화된 관용어라고 생각합니다(글 내용처럼 전자는 공통적인 관심사에 대한 템플릿, 후자는 중앙화되면서 검증된 도구를 의미하겠죠)

그래서 플랫폼 엔지니어링 내부에서의 golden path와 paved road는 기존과 다른 의미를 지니는 만큼 외래어로 병기를 하면 어떨까 생각합니다. 이후 다른 글에서 사용할 때 'Plaform engineeering paved road' => '플랫폼 엔지니어링 포장된 도로' 라고 표기되는 것이 조금 어색할 수 있다고 생각이 드는데, 자유롭게 의견 주시면 감사하겠습니다!

생각은 이렇게 드는데, 어떻게 하면 좋을지 좀 어렵네요...

2024-01-31 06:33 UTC, Geun-Oh approved these changes

2024-01-31 08:09 UTC, jjangga0214 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +*BigCo* 는 클라우드 및 자동화에 대해 대규모로 투자하고 있었습니다. 하지만 그럼에도 불구하고 인프라 및 운영 영역에서 전통적인 팀을 유지하고 있었어요. 이 '전통적인 팀'은 주된 기술 역량에 따라 구성되어 있었죠. 우리는 몇 가지 일반적인 변경 사항이 회사에서 어떻게 수행되는지 그 전 과정을 따라가 보았습니다. 각 변경 사항에는 여러 팀이 참여했습
🔎 오 매의 눈! 
감사합니다!

2024-01-31 08:22 UTC, jjangga0214 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +(**역주**: 플랫폼 엔지니어링의 영역에서는 '{{ Golden Path }}'(Golden Path)라는 용어도 종종 사용됩니다. '{{ Paved Road }}'(Paved Road) 와 둘다 "길"로 비유한다는 점은 공통점이지만, 서로 다른 개념입니다. 전자는 공통적인 관심사에 대한 템플릿에 가깝고, 후자는 중앙화되면서 검증된 도구를 의미합니다.)
아 그렇게 생각해주셨군요!
좋은 포인트라고 생각합니다 😊

제 개인적인 생각으로는, 낱말 그대로의 일반적 의미가 아닌, 특수한 의미에 따옴표나 큰따옴표를 넣는 것이 국문 표기법에 있다보니 
`'골든 패스'(Golden Path)` 나 `"포장된 도로"(Paved Road)`

처럼 표기하는 것이 저희 케이스에 딱이지 않을까 생각해 보았었습니다!
특히 영문과 병기하면 더욱이 *"이 단어엔 특수한 의미가 있어~"* 하는 냄새가 풀풀 나지 않을까 해서.. ㅋㅋㅋㅋ

아무래도 작은 따옴표보다 큰 따옴표가 좀 더 특수한 의미가 강조될 것 같기도 해서 이런 경우는 큰따옴표를 사용하는 것으로 할까 싶은 생각도 드네요 ㅎㅎ

다혜님 의견도 한번 같이 들어보아요 🙏

2024-02-07 02:37 UTC, flavono123 reviewed
병찬님께 슬랙 DM으로 드렸던 피드백 여기도 올려봅니다.
(이런식으로 번역하시는군요 ㅎㅎ 고생 많으십니다 👍 )

리뷰 단 라인들은, 제가 보다가 "원문을 봐야겠는데?" 싶어서 원문을 보고 온 부분들입니다.

2024-02-07 02:37 UTC, flavono123 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +이건 여러 면에서 우리에게 해를 끼쳐요. 우선 순수한 업무 처리량과 고객 요구에 대한 대응력에 부정적인 영향을 미치는 게 자명하죠. 그리고 우리는 종속성을 보다 효율적으로 관리하기 위한 보다 장기적인 계획을 세우도록 유도"당합니다". 이런 문화는, 어떤 결과던 하나의 단일 팀이 주된 책임을 지도록 하는 지향성을 저하시키고, 많은 팀의 동기 부여를 죽이는
```suggestion
이건 여러 면에서 우리에게 해를 끼쳐요. 우선 순수한 업무 처리량과 고객 요구에 대한 대응력에 부정적인 영향을 미치는 게 자명하죠. 그리고 우리는 종속성을 보다 효율적으로 관리하기 위한 보다 장기적인 계획을 세우도록 유도"당합니다". 이런 문화는, 어떤 결과던 하나의 단일 팀이 주된 책임을 지도록 하는 지향성(accountability)을 저하시키고, 많은 팀의 동기 부여를 죽이는 것을 목격했어요. 팀들은 쉽게 서로 책임을 전가하고 지속적인 개선 추구를 중단하게 될 수도 있습니다.
```
(개인적으로) 영단어'도' 어려움

2024-02-07 02:37 UTC, flavono123 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +우리는 이러한 유형의 접근 방식을 '{{ Superficial Private Cloud }}'(Superficial Private Cloud)라고 부릅니다. 즉, 중앙 집중식 제어의 양을 줄이려는 실제 의도 없이 매우 제한된 방식으로 딜리버리(Delivery) 팀이 사용할 수 있도록 하려는 접근방식입니다. 기존에 사용하던 가상화 플랫폼을 크게 바꾸지 않고
```suggestion
우리는 이러한 유형의 접근 방식을 '{{ Superficial Private Cloud }}'(Superficial Private Cloud)라고 부릅니다. 즉, 중앙에서 제어하는 양은 줄이지 않고 매우 제한된 방식으로 딜리버리(Delivery) 팀이 사용할 수 있도록 하려는 접근방식입니다. 기존에 사용하던 가상화 플랫폼을 크게 바꾸지 않고 포장만 그럴듯하게 하는 것이라 할 수 있죠.
```
원문: with no real intent to reduce the amount of centralised control

수식??을 줄이고 너무 직역에 가까운 표현을 바꿔 봤습니다.

2024-02-07 02:37 UTC, flavono123 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +## 기술 다양화로 항력 증가
```suggestion
## 기술 다양화로 항력(drag) 증가
```
(개인적으로) 영단어 뜻이 어려움..

2024-02-07 06:19 UTC, jjangga0214 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +이건 여러 면에서 우리에게 해를 끼쳐요. 우선 순수한 업무 처리량과 고객 요구에 대한 대응력에 부정적인 영향을 미치는 게 자명하죠. 그리고 우리는 종속성을 보다 효율적으로 관리하기 위한 보다 장기적인 계획을 세우도록 유도"당합니다". 이런 문화는, 어떤 결과던 하나의 단일 팀이 주된 책임을 지도록 하는 지향성을 저하시키고, 많은 팀의 동기 부여를 죽이는
오 리뷰 달아주셔서 너무 감사해요!

> It also damages a team’s own accountability for outcomes

accountability 를 한 단어로 번역하면 '책무성' 정도가 되지 않을까 하는데,
잘 쓰이지 않는 단어고 독자 입장서 편한 단어가 아닐 것 같아서 
"어떤 결과던 하나의 단일 팀이( -> 맥락상 저자가 말하고자 하는 의미를 의역) 주된 책임을 지도록 하는 지향성"
으로 의역해봤었습니다.

말씀처럼 accountability 원문도 달아두면 확실히 더 좋겠어요~

2024-02-07 06:21 UTC, jjangga0214 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +우리는 이러한 유형의 접근 방식을 '{{ Superficial Private Cloud }}'(Superficial Private Cloud)라고 부릅니다. 즉, 중앙 집중식 제어의 양을 줄이려는 실제 의도 없이 매우 제한된 방식으로 딜리버리(Delivery) 팀이 사용할 수 있도록 하려는 접근방식입니다. 기존에 사용하던 가상화 플랫폼을 크게 바꾸지 않고
오 좋습니다 반영하겠습니다!

2024-02-07 06:25 UTC, jjangga0214 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +## 기술 다양화로 항력 증가
그렇네요 영문을 달아주는게 확실히 나아보입니다 ㅎㅎ

여담으로 장애물, 저항, 마찰력 등의 뜻을 품고 있는데 마땅히 딱 표현할 단어가 없었어서 고민했어요
저항력이란 말도 너무 네거티브하고 강해서 맥락상 좀 어색하고..
그래서 물리학적인 단어로 항력이라고 하긴 했죠.
저도 약간 고민스런 부분이긴 했습니다.

2024-02-20 11:25 UTC, da-head0 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +(**역주**: 플랫폼 엔지니어링의 영역에서는 '{{ Golden Path }}'(Golden Path)라는 용어도 종종 사용됩니다. '{{ Paved Road }}'(Paved Road) 와 둘다 "길"로 비유한다는 점은 공통점이지만, 서로 다른 개념입니다. 전자는 공통적인 관심사에 대한 템플릿에 가깝고, 후자는 중앙화되면서 검증된 도구를 의미합니다.)
포장된 도로 라고 표기하는 것이 조금 어색할 수도 있다는 의견에 동의합니다. @jjangga0214 님 의견대로 원문을 병기하는 편이 좋을 것 같아요! 
링크나 주석을 다는 방법도 좋습니다.
https://www.scourt.go.kr/portal/gongbo/PeoplePopupView.work?gubun=24&seqNum=1608
법원 예시지만, 어떤 말을 인용할 때는 큰 따옴표를 쓰는 것 같습니다.

2024-02-20 11:30 UTC, da-head0 approved these changes

2024-02-20 11:58 UTC, jjangga0214 commented on articles/jjangga0214/0001-talk-about-platforms.md
> +(**역주**: 플랫폼 엔지니어링의 영역에서는 '{{ Golden Path }}'(Golden Path)라는 용어도 종종 사용됩니다. '{{ Paved Road }}'(Paved Road) 와 둘다 "길"로 비유한다는 점은 공통점이지만, 서로 다른 개념입니다. 전자는 공통적인 관심사에 대한 템플릿에 가깝고, 후자는 중앙화되면서 검증된 도구를 의미합니다.)
오 감사해요 법원 예시까지..!
알겠습니다 그렇게 관례를 정하면 되겠네요 ㅎㅎ

2024-02-24 07:26 UTC, merged