Translate/ Internal Devleper Platfrom vs Internal Developer Portal
awskrug/platform-engineering-glossary pull request #5
Opened 2024-02-03 22:24 UTC by Geun-Oh

https://romaricphilogene.substack.com/p/platform-engineering-7-internal-developer

요 글을 번역하고 관련 단어 추가했습니다.

기존 해송님 변경사항까지 반영해서 추가했습니다.

2024-02-03 22:58 UTC, Geun-Oh commented
호옹,,,혹시 Publish에서 404가 뜨는데 제가 설정에서 빠뜨린 부분이 있을까요..? 확인 한 번 해주시면 감사하겠습니다..!

2024-02-04 15:33 UTC, jjangga0214 commented
오 Internal Developer Platform 과 Internal Developer Portal 의 차이에 대해서 정리한 글이 있으면 좋겠다고 생각했는데 참 반가운 글입니다!! 감사해요 ㅎㅎ

2024-02-04 15:49 UTC, jjangga0214 requested changes

2024-02-04 15:49 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +id: 1732681
404는 이 부분 때문입니다!
id 는  (draft 던 아니던) 이미 게재된 글을 의미하는데, 
author 가 쓴 글 중 동일 id를 찾을 수 없어서 Not Found 가 나온것 같습니다.
아마 복사하시다가 실수하신 것 같습니다 ㅎㅎ
지우면 잘 작동할 것 같습니다!

2024-02-04 15:49 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +여러분 안녕하세요 👋,
아마도 글의 서두나 말미에 원문 링크를 깜빡 빠뜨리신 것 같습니다 ㅎㅎ

2024-02-04 15:49 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +# {{ Platform Engineering }} #7: {{ Internal Developer Platform }} vs. {{ Internal Developer Portal }}
글에서(또는 큰 문단에서) glossary 의 주요 단어가 처음 등장할 때에 한해, 
```
한글(영문)
``` 

식으로 표기하면 어떨까요?

이를 테면

```
{{ Platform Engineering }} #7: {{ Internal Developer Platform }}(Internal Developer Platform) vs. {{ Internal Developer Portal }}(Internal Developer Portal)
```

은 어떨까 합니다~ 
과도한 세레머니 같으면 작성자의 재량 하에 주요 단어가 아니거나 익숙한 단어는 안그래도 될 것 같지만요ㅎㅎ
(예: 위의 예에서 플랫폼 엔지니어링은 굳이 영문병기를 안 해도 된다고 생각할 수도 있을 것 같습니다.)

2024-02-04 15:49 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +- **{{ Synergistic Use }}**: {{ Internal Developer Platfrom }} 과 {{ Internal Developer Portal }}을 함께 사용하는 것은 {{ Self-Service }} 경험을 향상시킵니다. {{ Internal Developer Portal }}이 개발자들이 {{ Internal Develope
`Synergistic Use` 의 glossary 추가를 깜빡하신것 같습니당 ㅎㅎ
아니면.. 음 개인적으로 이 단어는 저자가 기술에 관한 용어라기보단 좀 보편적이고 일반적인 뜻으로 사용한 것 같아서 glossary 추가를 안해도 될 것 같기도 해요 ㅎㅎ (처음 추가하셨다가 이런 생각으로 빼신 것일수도 있겠네요)

2024-02-04 15:49 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +진짜 마법은 {{ Internal Developer Platform }}과 {{ Internal Developer Portal }}이 함께 사용될 때 발생합니다. {{ Internal Developer Platform }}은 강력한 백엔드 인프라와 자동화 기능을 제공하는 반면, {{ Internal Developer Portal }}은 사용자 친화적인 프
이거 빼먹으신 것 같아요 ㅎㅎ

`셀프 서비스` -> `{{ Self-Service }}`

2024-02-04 15:49 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +{{ Internal Developer Platform }}과 {{ Internal Developer Portal }}은 별개의 목적을 수행하지만, 이들을 통합하여 사용하면 개발자들에게 셀프 서비스 경험을 크게 향상시킬 수 있습니다. {{ Internal Developer Platform }}은 엔진 역할을 하며 자동화와 통합을 주도하는 반면, {{ In
`셀프 서비스` -> `{{ Self-Service }}`

2024-02-05 06:06 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +id: 1732681
아하 감사합니다!!

2024-02-05 06:10 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +# {{ Platform Engineering }} #7: {{ Internal Developer Platform }} vs. {{ Internal Developer Portal }}
아아 좋네요! 알겠습니다

2024-02-05 06:34 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +- **{{ Synergistic Use }}**: {{ Internal Developer Platfrom }} 과 {{ Internal Developer Portal }}을 함께 사용하는 것은 {{ Self-Service }} 경험을 향상시킵니다. {{ Internal Developer Portal }}이 개발자들이 {{ Internal Develope
맞아요ㅜㅜ 조금 고민이 되었어서,,,이런 단어들 다음 케이던스에 기회 되면 얘기해보면 좋을 것 같아요!

2024-02-06 07:48 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +id: 1732681
아 아닙니다 ㅎㅎ
말씀주신 덕분에 에러 시 대표 에러메시지 한줄+stacktrace 만 나오던 것을 전체 메세지가 나오도록 수정했어요~
<img width="553" alt="스크린샷 2024-02-06 오후 4 46 46" src="https://github.com/awskrug/platform-engineering-glossary/assets/28584151/6c9903d9-6ded-45c5-b3fd-b77a471edeb1">
허용되는 태그가 최대 4개인데 5개로 작성하셔서 그런 것 같습니다!

2024-02-12 08:34 UTC, jjangga0214 commented
오 배포되었군요!
https://github.com/awskrug/platform-engineering-glossary/pull/3#issuecomment-1918672421
혹시 이 작업부탁드려도 될까요?
감사합니다 :)

2024-02-12 08:38 UTC, Geun-Oh commented
> 오 배포되었군요! [#3 (comment)](https://github.com/awskrug/platform-engineering-glossary/pull/3#issuecomment-1918672421) 혹시 괜찮으시다면 이 작업부탁드려도 될까요? 감사합니다 :)

완료했습니다! 감사합니다 :)

2024-02-12 09:23 UTC, jjangga0214 requested changes

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +- **{{ Synergistic Use }}**: {{ Internal Developer Platfrom }} 과 {{ Internal Developer Portal }}을 함께 사용하는 것은 {{ Self-Service }} 경험을 향상시킵니다. {{ Internal Developer Portal }}이 개발자들이 {{ Internal Develope
아 추가! 저도 놓쳤었네요!
`{{ Internal Developer Platfrom }}` 에서 Platfrom 이 오타입니다 ㅎㅎ

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +저는 [Qovery](https://www.qovery.com/)({{ Internal Developer Platform }})의 CEO이자 공동창업자인 Romaric Philogene 이고, 이 글은 제가 Substack에 올리는 7번째 글이네요. 제 이전 글에서, 저는 2024년의 {{ Platform Engineering }}에 대한 예상들을 공유했
Romaric Philogene 와 같이 사람 이름이 등장할 때, 작성자 재량으로 프로필 링크를 달아주면 어떨까요?
LinkedIn, X(twitter), GitHub 등등..

https://github.com/awskrug/platform-engineering-glossary/pull/3#discussion_r1468296418
에서도 일관성 있게 동일한 취지로 언급해보았습니다 ㅎㅎ

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +- **{{ Internal Developer Platform }}**: 개발자들이 전반적인 소프트웨어 생명주기(SDLC)를 자동적으로 관리할 수 있도록하는 종합적인 도구와 프로세스(process)의 모음이다. 이는 다양한 개발(development), 운영(deployment), 모니터링(monitoring) 도구들을 하나의 결합된 시스템에 통합했으며,
2가지 개인적인 제안이 있습니다!

## 1. 번역
 
```
소프트웨어 생명주기(SDLC) -> 소프트웨어 개발 수명 주기
``` 

용례를 조금 찾아보면서 `소프트웨어 개발 수명 주기` 로 번역하면 어떨까 생각이 드는데, 혹 괜찮으실까요?

<img width="727" alt="스크린샷 2024-02-12 오후 6 09 18" src="https://github.com/awskrug/platform-engineering-glossary/assets/28584151/33db3a73-9a68-4e43-88c9-50bc4db018bc">

*(위: Google 검색 최상위 4건이에요)*

## 2. Glossary 추가
(플랫폼 엔지니어링 관련) 다른 글에서도 자주는 아니지만 어쩌다 간혹 등장하는것 같습니다. 
해서 glossary 에 추가하면 어떨까 한번 생각해봤습니다~
혹시 형근님은 어떻게 생각하세요?
(cc: @da-head0 )


## P.S.

```
있도록하는 -> 있도록 하는
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +오늘 저는 {{ Internal Developer Platform }}(Internal Developer Platform)과 {{ Internal Developer Portal }}(Internal Developer Portal)이 무엇이고, 이 두 플랫폼이 어떻게 {{ Platform Engineer }}(Platform Engineer)들에 의해 사용
```
제공하고자하는 -> 제공하고자 하는 
명확히하고자 -> 명확히 하고자
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +> {{ Internal Developer Portal }}은 직관적인 인터페이스(interface)을 제공하지만, {{ Internal Developer Platform }}은 엔진으로서 자동화(automation)와 통합(integration)을 목적으로 동작합니다.
```
인터페이스(interface)을 -> 인터페이스(interface)를
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +{{ Internal Developer Platform }}은 개발자들이 개발에서 배포까지의 전체 애플리케이션(application) 생명 주기를 자동으로 관리할 수 있도록하는 환경입니다. 이는 애플리케이션 개발 및 관리에 있어 IT와 {{ DevOps }}에 크게 의존하고 있기에 나타나는 비효율성과 상호의존성에 대한 해답으로써 나타났습니다.
```
있도록하는 -> 있도록 하는 
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +종합적인 도구와 서비스를 제공함으로써, {{ Internal Developer Platform }}은 개발자들이 독립적으로 애플리케이션을 구성, 배포, 관리할 수 있도록하여 효율성과 생산성을 향상시켰습니.
```
향상시켰습니. -> 향상시켰습니다.
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +{{ Internal Developer Platform }}은 유연하게 기존의 {{ DevOps }}와 기술 스택(stack)들에 통합되고, 기존의 프로세스를 유연하게 하고 강화하는 통합 계층으로써 동작합니다. 이는 소프트웨어 개발, 배포, 관리 등에 사용되는 다양한 도구와 서비스가 융합되는 중앙 집중화된 플랫폼을 제공함으로써 생태계에 부합합니다. 이러한
```
기존의 스택의 -> 기존 스택의
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +{{ Internal Developer Platform }}이 소프트웨어 개발자들의 문제의 일부를 해결하는 것은 맞지만, 모든 것을 해결하지는 않는다. 이 곳이 {{ Internal Developer Portal }}이 필요한 지점입니다.
```
이 곳이 -> 이곳이
```

2024-02-12 09:23 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +{{ Internal Developer Portal }}은 IT 자원들에 대한 출입문이다. 이것은 개발자들이 도구, 애플리케이션, API들, 문서, 그리고 지원 사항에 대해 접근할 수 있도록 하는 사용자 인터페이스입니다. 이는 접근성과 사용성에 초점을 두어 디자인되는데, 당신의 IT {{ Infrastructure }}의 '얼굴'을 생각하면 이해하기 어렵
```
출입문이다 -> 출입문입니다
API들 -> API
```

2024-02-12 09:35 UTC, jjangga0214 requested changes

2024-02-12 09:35 UTC, jjangga0214 commented on glossary.csv
> +Infrastructure,인프라스트럭처
1. 등재 여부 

저는 개인적으로 Infrastructure 가 상당히 범용적인 단어라서 
Glossary 에 따로 추가하지는 않았었는데, 등재가 좋을지 잘 모르겠습니다.
@da-head0 어떻게 생각하시나요?

2. 번역

저는 번역할 때 인프라스트럭처가 좀 긴 것 같다는 생각을 했었습니다.

저는 `우리나라 사람들은 이미 인프라라는 단어에 더 익숙하지 않을까?`
생각해서 아래와 같이 번역하긴 했었습니다. 짧은 단어표현으로 글이 더 간결해져서 좋기도 했구요.

```csv
Delivery Infrastructure,딜리버리 인프라
Delivery Infrastructure Platform,딜리버리 인프라 플랫폼
```

`Infrastructure` 도 인프라로 번역하는 것에 대해서 어떻게 생각하실까요?

2024-02-12 09:38 UTC, jjangga0214 requested changes

2024-02-12 09:38 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +5. **Better Resource Management**: The Portal can provide insights and analytics from the Internal Developer Platform, helping teams optimize resource usage and performance.
이 부분은 WIP 이신가요?
혹시나 해서 여쭙습니다 ㅎㅎ

2024-02-13 02:23 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +5. **Better Resource Management**: The Portal can provide insights and analytics from the Internal Developer Platform, helping teams optimize resource usage and performance.
앗 작업하면서 실수를 한 것 같네요..! 감사합니다 👍

2024-02-13 02:26 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +저는 [Qovery](https://www.qovery.com/)({{ Internal Developer Platform }})의 CEO이자 공동창업자인 Romaric Philogene 이고, 이 글은 제가 Substack에 올리는 7번째 글이네요. 제 이전 글에서, 저는 2024년의 {{ Platform Engineering }}에 대한 예상들을 공유했
오호 좋은 의견이네요!! 작성자 재량이면,,,원 작성자에게 직접 여쭈어서 다는 것일까요..?

2024-02-13 02:27 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +- **{{ Internal Developer Platform }}**: 개발자들이 전반적인 소프트웨어 생명주기(SDLC)를 자동적으로 관리할 수 있도록하는 종합적인 도구와 프로세스(process)의 모음이다. 이는 다양한 개발(development), 운영(deployment), 모니터링(monitoring) 도구들을 하나의 결합된 시스템에 통합했으며,
이건 개발 생명 주기가 올바른 표현인 것 같네요. 감사합니다.
오타가 많네요..감사합니다 :)

2024-02-13 03:21 UTC, jjangga0214 commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +저는 [Qovery](https://www.qovery.com/)({{ Internal Developer Platform }})의 CEO이자 공동창업자인 Romaric Philogene 이고, 이 글은 제가 Substack에 올리는 7번째 글이네요. 제 이전 글에서, 저는 2024년의 {{ Platform Engineering }}에 대한 예상들을 공유했
아아 제가 의미한 작성자 재량이라는 것은 
Romaric Philogene 님의 LinkedIn, X(twitter), GitHub 계정 등 중에서 
'번역 작성자' 이신 형근님의 재량으로 택일하여 
링크를 다는 것을 의도했습니다~
아니면 Romaric Philogene 님께 여쭈어보아도 좋구요
(아마 대부분 좋아하지지 않을까 싶네요 ㅎㅎ)

2024-02-18 04:08 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +저는 [Qovery](https://www.qovery.com/)({{ Internal Developer Platform }})의 CEO이자 공동창업자인 Romaric Philogene 이고, 이 글은 제가 Substack에 올리는 7번째 글이네요. 제 이전 글에서, 저는 2024년의 {{ Platform Engineering }}에 대한 예상들을 공유했
아하아하 좋은 의견이네요! 추가해보겠습니다.

2024-02-18 04:14 UTC, Geun-Oh commented on glossary.csv
> +Infrastructure,인프라스트럭처
요곳도 그럼 인프라로 통일해서 올려두겠습니다! 추후에 논의해보면 좋을 것 같네용

2024-02-18 04:15 UTC, Geun-Oh commented on articles/Geun-Oh/internal_developer_platform_vs_internal_developer_portal.md
> +저는 [Qovery](https://www.qovery.com/)({{ Internal Developer Platform }})의 CEO이자 공동창업자인 Romaric Philogene 이고, 이 글은 제가 Substack에 올리는 7번째 글이네요. 제 이전 글에서, 저는 2024년의 {{ Platform Engineering }}에 대한 예상들을 공유했
Substack.com 프로필을 추가해두었습니다~타 프로필보다 해당 글이 작성된 플랫폼 프로필이 가장 적합할 것 같기도 하고, 해당 작성자 분께서 Platform Engineering Tips라는 시리즈를 Substack에서 연재 중이셔서 해당 시리즈가 잘 보일 수 있을 것 같아 첨부했습니다.

2024-02-20 11:22 UTC, da-head0 commented on glossary.csv
> +Infrastructure,인프라스트럭처
Infrastructure -> 인프라 로 통일하면 좋을 것 같습니다!

2024-02-20 11:30 UTC, da-head0 approved these changes

2024-02-24 12:11 UTC, merged